# https://github.com/golangci/golangci-lint/blob/HEAD/.golangci.reference.yml
version: "2"
linters:
  default: none
  enable:
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - revive
    - staticcheck

  settings:
    gocritic:
      disable-all: true
      enabled-checks:
        # https://go-critic.com/overview.html#appendassign
        - appendAssign
        # https://go-critic.com/overview.html#argorder
        - argOrder
        # https://go-critic.com/overview.html#assignop
        - assignOp
        # https://go-critic.com/overview.html#badcall
        - badCall
        # https://go-critic.com/overview.html#badcond
        - badCond
        # https://go-critic.com/overview.html#captlocal
        - captLocal
        # https://go-critic.com/overview.html#caseorder
        - caseOrder
        # https://go-critic.com/overview.html#codegencomment
        - codegenComment
        # https://go-critic.com/overview.html#commentformatting
        - commentFormatting
        # https://go-critic.com/overview.html#defaultcaseorder
        - defaultCaseOrder
        # https://go-critic.com/overview.html#deprecatedcomment
        - deprecatedComment
        # https://go-critic.com/overview.html#duparg
        - dupArg
        # https://go-critic.com/overview.html#dupbranchbody
        - dupBranchBody
        # https://go-critic.com/overview.html#dupcase
        - dupCase
        # https://go-critic.com/overview.html#dupsubexpr
        - dupSubExpr
        # https://go-critic.com/overview.html#elseif
        - elseif
        # https://go-critic.com/overview.html#exitafterdefer
        - exitAfterDefer
        # https://go-critic.com/overview.html#flagderef
        - flagDeref
        # https://go-critic.com/overview.html#flagname
        - flagName
        # https://go-critic.com/overview.html#ifelsechain
        - ifElseChain
        # https://go-critic.com/overview.html#mapkey
        - mapKey
        # https://go-critic.com/overview.html#newderef
        - newDeref
        # https://go-critic.com/overview.html#offby1
        - offBy1
        # https://go-critic.com/overview.html#regexpmust
        - regexpMust
        # https://go-critic.com/overview.html#singlecaseswitch
        - singleCaseSwitch
        # https://go-critic.com/overview.html#sloppylen
        - sloppyLen
        # https://go-critic.com/overview.html#sloppytypeassert
        - sloppyTypeAssert
        # https://go-critic.com/overview.html#switchtrue
        - switchTrue
        # https://go-critic.com/overview.html#typeswitchvar
        - typeSwitchVar
        # https://go-critic.com/overview.html#underef
        - underef
        # https://go-critic.com/overview.html#unlambda
        - unlambda
        # https://go-critic.com/overview.html#unslice
        - unslice
        # https://go-critic.com/overview.html#valswap
        - valSwap
        # https://go-critic.com/overview.html#wrapperfunc
        - wrapperFunc

    govet:
      enable:
        - appends
        - asmdecl
        - assign
        - atomic
        - bools
        - buildtag
        - cgocall
        - composites
        - copylocks
        - deepequalerrors
        - defers
        - directive
        - errorsas
        - framepointer
        - hostport
        - httpresponse
        - ifaceassert
        - inline
        - lostcancel
        - nilfunc
        - printf
        - shift
        - sigchanyzer
        - slog
        - stdmethods
        - stdversion
        - stringintconv
        - structtag
        - testinggoroutine
        - tests
        - timeformat
        - unmarshal
        - unreachable
        - unsafeptr
        - unusedresult
        - waitgroup

    revive:
      enable-default-rules: false
      rules:
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#blank-imports
        - name: blank-imports
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#context-as-argument
        - name: context-as-argument
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#context-keys-type
        - name: context-keys-type
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#dot-imports
        - name: dot-imports
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#empty-block
        - name: empty-block
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#error-naming
        - name: error-naming
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#error-return
        - name: error-return
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#error-strings
        - name: error-strings
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#errorf
        - name: errorf
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#exported
        - name: exported
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#increment-decrement
        - name: increment-decrement
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#indent-error-flow
        - name: indent-error-flow
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#package-comments
        - name: package-comments
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#range
        - name: range
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#receiver-naming
        - name: receiver-naming
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#redefines-builtin-id
        - name: redefines-builtin-id
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#superfluous-else
        - name: superfluous-else
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#time-naming
        - name: time-naming
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unexported-return
        - name: unexported-return
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unreachable-code
        - name: unreachable-code
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
        - name: unused-parameter
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#var-declaration
        - name: var-declaration
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#var-naming
        - name: var-naming

    staticcheck:
      checks:
        # https://staticcheck.dev/docs/checks/#QF1001
        - "QF1001"
        # https://staticcheck.dev/docs/checks/#QF1002
        - "QF1002"
        # https://staticcheck.dev/docs/checks/#QF1003
        - "QF1003"
        # https://staticcheck.dev/docs/checks/#QF1004
        - "QF1004"
        # https://staticcheck.dev/docs/checks/#QF1005
        - "QF1005"
        # https://staticcheck.dev/docs/checks/#QF1006
        - "QF1006"
        # https://staticcheck.dev/docs/checks/#QF1007
        - "QF1007"
        # https://staticcheck.dev/docs/checks/#QF1008
        - "QF1008"
        # https://staticcheck.dev/docs/checks/#QF1009
        - "QF1009"
        # https://staticcheck.dev/docs/checks/#QF1010
        - "QF1010"
        # https://staticcheck.dev/docs/checks/#QF1011
        - "QF1011"
        # https://staticcheck.dev/docs/checks/#QF1012
        - "QF1012"
        # https://staticcheck.dev/docs/checks/#S1000
        - "S1000"
        # https://staticcheck.dev/docs/checks/#S1001
        - "S1001"
        # https://staticcheck.dev/docs/checks/#S1002
        - "S1002"
        # https://staticcheck.dev/docs/checks/#S1003
        - "S1003"
        # https://staticcheck.dev/docs/checks/#S1004
        - "S1004"
        # https://staticcheck.dev/docs/checks/#S1005
        - "S1005"
        # https://staticcheck.dev/docs/checks/#S1006
        - "S1006"
        # https://staticcheck.dev/docs/checks/#S1007
        - "S1007"
        # https://staticcheck.dev/docs/checks/#S1008
        - "S1008"
        # https://staticcheck.dev/docs/checks/#S1009
        - "S1009"
        # https://staticcheck.dev/docs/checks/#S1010
        - "S1010"
        # https://staticcheck.dev/docs/checks/#S1011
        - "S1011"
        # https://staticcheck.dev/docs/checks/#S1012
        - "S1012"
        # https://staticcheck.dev/docs/checks/#S1016
        - "S1016"
        # https://staticcheck.dev/docs/checks/#S1017
        - "S1017"
        # https://staticcheck.dev/docs/checks/#S1018
        - "S1018"
        # https://staticcheck.dev/docs/checks/#S1019
        - "S1019"
        # https://staticcheck.dev/docs/checks/#S1020
        - "S1020"
        # https://staticcheck.dev/docs/checks/#S1021
        - "S1021"
        # https://staticcheck.dev/docs/checks/#S1023
        - "S1023"
        # https://staticcheck.dev/docs/checks/#S1024
        - "S1024"
        # https://staticcheck.dev/docs/checks/#S1025
        - "S1025"
        # https://staticcheck.dev/docs/checks/#S1028
        - "S1028"
        # https://staticcheck.dev/docs/checks/#S1029
        - "S1029"
        # https://staticcheck.dev/docs/checks/#S1030
        - "S1030"
        # https://staticcheck.dev/docs/checks/#S1031
        - "S1031"
        # https://staticcheck.dev/docs/checks/#S1032
        - "S1032"
        # https://staticcheck.dev/docs/checks/#S1033
        - "S1033"
        # https://staticcheck.dev/docs/checks/#S1034
        - "S1034"
        # https://staticcheck.dev/docs/checks/#S1035
        - "S1035"
        # https://staticcheck.dev/docs/checks/#S1036
        - "S1036"
        # https://staticcheck.dev/docs/checks/#S1037
        - "S1037"
        # https://staticcheck.dev/docs/checks/#S1038
        - "S1038"
        # https://staticcheck.dev/docs/checks/#S1039
        - "S1039"
        # https://staticcheck.dev/docs/checks/#S1040
        - "S1040"
        # https://staticcheck.dev/docs/checks/#SA1000
        - "SA1000"
        # https://staticcheck.dev/docs/checks/#SA1001
        - "SA1001"
        # https://staticcheck.dev/docs/checks/#SA1002
        - "SA1002"
        # https://staticcheck.dev/docs/checks/#SA1003
        - "SA1003"
        # https://staticcheck.dev/docs/checks/#SA1004
        - "SA1004"
        # https://staticcheck.dev/docs/checks/#SA1005
        - "SA1005"
        # https://staticcheck.dev/docs/checks/#SA1006
        - "SA1006"
        # https://staticcheck.dev/docs/checks/#SA1007
        - "SA1007"
        # https://staticcheck.dev/docs/checks/#SA1008
        - "SA1008"
        # https://staticcheck.dev/docs/checks/#SA1010
        - "SA1010"
        # https://staticcheck.dev/docs/checks/#SA1011
        - "SA1011"
        # https://staticcheck.dev/docs/checks/#SA1012
        - "SA1012"
        # https://staticcheck.dev/docs/checks/#SA1013
        - "SA1013"
        # https://staticcheck.dev/docs/checks/#SA1014
        - "SA1014"
        # https://staticcheck.dev/docs/checks/#SA1015
        - "SA1015"
        # https://staticcheck.dev/docs/checks/#SA1016
        - "SA1016"
        # https://staticcheck.dev/docs/checks/#SA1017
        - "SA1017"
        # https://staticcheck.dev/docs/checks/#SA1018
        - "SA1018"
        # https://staticcheck.dev/docs/checks/#SA1019
        - "SA1019"
        # https://staticcheck.dev/docs/checks/#SA1020
        - "SA1020"
        # https://staticcheck.dev/docs/checks/#SA1021
        - "SA1021"
        # https://staticcheck.dev/docs/checks/#SA1023
        - "SA1023"
        # https://staticcheck.dev/docs/checks/#SA1024
        - "SA1024"
        # https://staticcheck.dev/docs/checks/#SA1025
        - "SA1025"
        # https://staticcheck.dev/docs/checks/#SA1026
        - "SA1026"
        # https://staticcheck.dev/docs/checks/#SA1027
        - "SA1027"
        # https://staticcheck.dev/docs/checks/#SA1028
        - "SA1028"
        # https://staticcheck.dev/docs/checks/#SA1029
        - "SA1029"
        # https://staticcheck.dev/docs/checks/#SA1030
        - "SA1030"
        # https://staticcheck.dev/docs/checks/#SA1031
        - "SA1031"
        # https://staticcheck.dev/docs/checks/#SA1032
        - "SA1032"
        # https://staticcheck.dev/docs/checks/#SA2000
        - "SA2000"
        # https://staticcheck.dev/docs/checks/#SA2001
        - "SA2001"
        # https://staticcheck.dev/docs/checks/#SA2002
        - "SA2002"
        # https://staticcheck.dev/docs/checks/#SA2003
        - "SA2003"
        # https://staticcheck.dev/docs/checks/#SA3000
        - "SA3000"
        # https://staticcheck.dev/docs/checks/#SA3001
        - "SA3001"
        # https://staticcheck.dev/docs/checks/#SA4000
        - "SA4000"
        # https://staticcheck.dev/docs/checks/#SA4001
        - "SA4001"
        # https://staticcheck.dev/docs/checks/#SA4003
        - "SA4003"
        # https://staticcheck.dev/docs/checks/#SA4004
        - "SA4004"
        # https://staticcheck.dev/docs/checks/#SA4005
        - "SA4005"
        # https://staticcheck.dev/docs/checks/#SA4006
        - "SA4006"
        # https://staticcheck.dev/docs/checks/#SA4008
        - "SA4008"
        # https://staticcheck.dev/docs/checks/#SA4009
        - "SA4009"
        # https://staticcheck.dev/docs/checks/#SA4010
        - "SA4010"
        # https://staticcheck.dev/docs/checks/#SA4011
        - "SA4011"
        # https://staticcheck.dev/docs/checks/#SA4012
        - "SA4012"
        # https://staticcheck.dev/docs/checks/#SA4013
        - "SA4013"
        # https://staticcheck.dev/docs/checks/#SA4014
        - "SA4014"
        # https://staticcheck.dev/docs/checks/#SA4015
        - "SA4015"
        # https://staticcheck.dev/docs/checks/#SA4016
        - "SA4016"
        # https://staticcheck.dev/docs/checks/#SA4017
        - "SA4017"
        # https://staticcheck.dev/docs/checks/#SA4018
        - "SA4018"
        # https://staticcheck.dev/docs/checks/#SA4019
        - "SA4019"
        # https://staticcheck.dev/docs/checks/#SA4020
        - "SA4020"
        # https://staticcheck.dev/docs/checks/#SA4021
        - "SA4021"
        # https://staticcheck.dev/docs/checks/#SA4022
        - "SA4022"
        # https://staticcheck.dev/docs/checks/#SA4023
        - "SA4023"
        # https://staticcheck.dev/docs/checks/#SA4024
        - "SA4024"
        # https://staticcheck.dev/docs/checks/#SA4025
        - "SA4025"
        # https://staticcheck.dev/docs/checks/#SA4026
        - "SA4026"
        # https://staticcheck.dev/docs/checks/#SA4027
        - "SA4027"
        # https://staticcheck.dev/docs/checks/#SA4028
        - "SA4028"
        # https://staticcheck.dev/docs/checks/#SA4029
        - "SA4029"
        # https://staticcheck.dev/docs/checks/#SA4030
        - "SA4030"
        # https://staticcheck.dev/docs/checks/#SA4031
        - "SA4031"
        # https://staticcheck.dev/docs/checks/#SA4032
        - "SA4032"
        # https://staticcheck.dev/docs/checks/#SA5000
        - "SA5000"
        # https://staticcheck.dev/docs/checks/#SA5001
        - "SA5001"
        # https://staticcheck.dev/docs/checks/#SA5002
        - "SA5002"
        # https://staticcheck.dev/docs/checks/#SA5003
        - "SA5003"
        # https://staticcheck.dev/docs/checks/#SA5004
        - "SA5004"
        # https://staticcheck.dev/docs/checks/#SA5005
        - "SA5005"
        # https://staticcheck.dev/docs/checks/#SA5007
        - "SA5007"
        # https://staticcheck.dev/docs/checks/#SA5008
        - "SA5008"
        # https://staticcheck.dev/docs/checks/#SA5009
        - "SA5009"
        # https://staticcheck.dev/docs/checks/#SA5010
        - "SA5010"
        # https://staticcheck.dev/docs/checks/#SA5011
        - "SA5011"
        # https://staticcheck.dev/docs/checks/#SA5012
        - "SA5012"
        # https://staticcheck.dev/docs/checks/#SA6000
        - "SA6000"
        # https://staticcheck.dev/docs/checks/#SA6001
        - "SA6001"
        # https://staticcheck.dev/docs/checks/#SA6002
        - "SA6002"
        # https://staticcheck.dev/docs/checks/#SA6003
        - "SA6003"
        # https://staticcheck.dev/docs/checks/#SA6005
        - "SA6005"
        # https://staticcheck.dev/docs/checks/#SA6006
        - "SA6006"
        # https://staticcheck.dev/docs/checks/#SA9001
        - "SA9001"
        # https://staticcheck.dev/docs/checks/#SA9002
        - "SA9002"
        # https://staticcheck.dev/docs/checks/#SA9003
        - "SA9003"
        # https://staticcheck.dev/docs/checks/#SA9004
        - "SA9004"
        # https://staticcheck.dev/docs/checks/#SA9005
        - "SA9005"
        # https://staticcheck.dev/docs/checks/#SA9006
        - "SA9006"
        # https://staticcheck.dev/docs/checks/#SA9007
        - "SA9007"
        # https://staticcheck.dev/docs/checks/#SA9008
        - "SA9008"
        # https://staticcheck.dev/docs/checks/#SA9009
        - "SA9009"
        # https://staticcheck.dev/docs/checks/#ST1001
        - "ST1001"
        # https://staticcheck.dev/docs/checks/#ST1005
        - "ST1005"
        # https://staticcheck.dev/docs/checks/#ST1006
        - "ST1006"
        # https://staticcheck.dev/docs/checks/#ST1008
        - "ST1008"
        # https://staticcheck.dev/docs/checks/#ST1011
        - "ST1011"
        # https://staticcheck.dev/docs/checks/#ST1012
        - "ST1012"
        # https://staticcheck.dev/docs/checks/#ST1013
        - "ST1013"
        # https://staticcheck.dev/docs/checks/#ST1015
        - "ST1015"
        # https://staticcheck.dev/docs/checks/#ST1017
        - "ST1017"
        # https://staticcheck.dev/docs/checks/#ST1018
        - "ST1018"
        # https://staticcheck.dev/docs/checks/#ST1019
        - "ST1019"
        # https://staticcheck.dev/docs/checks/#ST1023
        - "ST1023"

formatters:
  enable:
    - goimports
    - gofumpt
    - golines

issues:
  max-issues-per-linter: 50
  max-same-issues: 10

run:
  timeout: 5m
  tests: true
